name: CI

on:
  # Run the build for pushes and pull requests targeting main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout and setup
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install and build
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      # Run linkcheck, propagate linkcheck failure through grep pipe
      - name: Linkcheck
        run: |
          set -o pipefail
          yarn linkcheck 2>/dev/null | grep -v "https://twitter.com" | grep -v "landing.dmnd.work" | grep "Getting links from\|BROKEN"
        continue-on-error: false
