name: Update submodule
on:
  repository_dispatch:
    types:
      - update-submodule
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
      
      - name: Fetch and rebase
        run: |
          git fetch
          git pull --rebase
      
      - name: Update submodule
        run: |
          git submodule update --init --recursive --checkout -f --remote -- "${{github.event.client_payload.module}}"
      
      - name: Commit changes if needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "deploy: ${{github.event.client_payload.module}} - ${{github.event.client_payload.sha}}"
            echo "CHANGES_MADE=true" >> $GITHUB_ENV
          else
            echo "No changes to commit"
            echo "CHANGES_MADE=false" >> $GITHUB_ENV
          fi
      
      - name: Pull again before push
        if: env.CHANGES_MADE == 'true'
        run: git pull --rebase
      
      - name: Push changes
        if: env.CHANGES_MADE == 'true'
        run: git push
